CUDA_VISIBLE_DEVICES=0 python tools/train_mean_teacher.py \
--config-file "configs/pap/e2e_mask_rcnn_R_50_FPN_1x.yaml" \
--gpuid '0' \
MODEL.RELATION_NMS.WEIGHT 1. MODEL.RELATION_NMS.ALPHA 0. MODEL.RELATION_NMS.LOSS 1. MODEL.RELATION_NMS.D_LOSS 0. \
MODEL.RELATION_NMS.GAMMA 1. MODEL.RELATION_NMS.REG_IOU True MODEL.RELATION_NMS.REG_IOU_MSK False \
MT.ALPHA 0.99 MT.ALPHA_RAMPUP 0.99 MT.LAMBDA 5. MT.RAMPUP_STEP 250 MT.RAMPDOWN_STEP 250 \
MODEL.RELATION_NMS.USE_RELATION_NMS True MT.TEMP 0.5 MT.SHARPEN True \
MT.START_MT 1000 MT.AUG_S 1 \
MT.CLS_LOSS_TYPE 'bce' SOLVER.IMS_PER_BATCH 4 \
MT.CLS_LOSS 0.2 \
MT.MEAN_TARGET True \
MT.FLIP True \
MT.CONF_PAIR True \
MODEL.META_ARCHITECTURE 'GeneralizedRCNN' \
MODEL.ROI_BOX_HEAD.DO 0.5 MODEL.RELATION_NMS.DO 0.5 \
SOLVER.CHECKPOINT_PERIOD 50 MT.AUG True \
MT.CLS_NEG True MT.HARD_NEG True MT.CLS_BALANCE_WEIGHT 1.5 MT.RANK_FILTER 0.2 \
MT.FG_HINT 1. MT.T_ADAPT True \
DATASETS.NO_LABEL True \
DATASETS.GEN_TRUE 0 \
DATASETS.TUNE_SOURCE False SOLVER.BASE_LR 0.005