MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
#  WEIGHT: None #"e2e_mask_rcnn_R_50_FPN_1x.pth"
  #"e2e_mask_rcnn_R_50_FPN_1x.pth"
  #"/media/amanda/SSD1/PapSeg/maskrcnn-benchmark/relation_F150_M0_FG0.05_lr0.002500_s(30000, 45000)_b2/model_final.pth"
  #"/media/amanda/HDD2T_2/cell-nuclei-segmentation/weight/e2e_mask_rcnn_R_50_FPN_1x.pth"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
    OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "PRCNNFeatureExtractor" #PRCNNFeatureExtractor
    PREDICTOR: "PRCNNPredictor"
    POOLER_RESOLUTION: 25
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 25
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MASK_ON: True
  RELATION_NMS:
    IOU_METHOD: 'n'
    USE_RELATION_NMS: False
    USE_IOU: False
    MUTRELATION: False
    FIRST_N: 90
    THREAD: (0.5, )
    ROI_FEAT_DIM: 1024
    APPEARANCE_FEAT_DIM: 128
    GEO_FEAT_DIM: 64
    FC_DIM: (64, 16)
    GROUP: 16
    HID_DIM: (1024, 1024, 128)
    CLASS_AGNOSTIC: False
    FG_THREAD: 0.1
#    MERGE_METHOD: 0
    MERGE_METHOD: 0
    POS_NMS: 0.55
    CLS_WISE_RELATION: False
    TOPK: 40
    TAG: '_5'
    APPEARANCE_INTER: True
    CONCAT: False # if True, then concate inter and intra feature, else add
  RELATION_MASK:

    BINARY: False
    USE_PRE_FEATURE: False
    PRE_NORM: False
    DEEP_SUPER: True
    TYPE: 'LIAM' # CIAM, CAM
    SAME_PREDICTOR: False
    CAM: False
    CIAM: True
    TRAIN_CENTER_ONLY: False
    PROTO: False
    ALPHA: 0.5
    CENTER_PER_CLASS: 8
    CENTER_TOPK: 20
    RANK: True
    XY_COOR: True
    NORM: -1 #1 : SUM CHANNEL 2: L2 NORM -1: NO NORM
    IOU_COOR: False
    FEATURE_EXTRACTOR: "RoiAlignMaskFeatureExtractor" #"SameSizeRoiAlignMaskFeatureExtractor" # 'RoiAlignMaskFeatureExtractor' #'SameFeatureMask' #'RoiAlignMaskFeatureExtractor'
    EXTRACTOR_CHANNEL: 16
#    ROI_FEAT_DIM: 1024
    USE_RELATION: False
    APPEARANCE_FEAT_DIM: 128
    GEO_FEAT_DIM:  64
    FC_DIM: (64, 16)
    GROUP: 16
    HID_DIM: (1024, 1024,)
    TOPK: 128
    CLSWIZE: True
  IOU_HEAD:
    USE_IOU_MASK: False
DATASETS:
  TRAIN: ("papnuclei_train",)
  TEST: ("papnuclei_test",)
  VAL: ("papnuclei_val",)
  TRAIN_FOLD: (1, 2)
  TEST_FOLD: (3,)
  MODE_IN_TEST: 'val'
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.0010 #0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (45000,) #(30000, 45000) #(60000, 80000)
  MAX_ITER: 50000 #50000 #30000 #90000

